server:
  port: 8006

spring:
  application:
    name: cloud-payment-service-consul
  cloud:
    consul:
      host: 49.235.190.5
      port: 8500
      discovery:
        service-name: ${spring.application.name}
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: org.gjt.mm.mysql.Driver
    url: jdbc:mysql://49.235.190.5:3306/cloud?useUnicode=true&characterEncoding=utf-8&useSSL=false&autoReconnect=true&failOverReadOnly=false
    username: root
    password: 999piyanning


mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.xxt.springcloud.entities


