server:
  port: 8004

spring:
  application:
    name: cloud-payment-service
  cloud:
    zookeeper:
      #zk的连接信息
      connect-string: 49.235.190.5:2181
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: org.gjt.mm.mysql.Driver
    url: jdbc:mysql://49.235.190.5:3306/cloud?useUnicode=true&characterEncoding=utf-8&useSSL=false&autoReconnect=true&failOverReadOnly=false
    username: root
    password: 999piyanning


mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.xxt.springcloud.entities


