server:
  port: 80

spring:
  application:
    name: cloud-order-service
  cloud:
    consul:
      host: 49.235.190.5
      port: 8500
      discovery:
        service-name: ${spring.application.name}