server:
  port: 8001

spring:
  application:
    name: cloud-payment-hystrix-service
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: org.gjt.mm.mysql.Driver
    url: jdbc:mysql://49.235.190.5:3306/cloud?useUnicode=true&characterEncoding=utf-8&useSSL=false&autoReconnect=true&failOverReadOnly=false
    username: root
    password: 999piyanning


mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.xxt.springcloud.entities

eureka:
  client:
    register-with-eureka: true   #是否将自己注册到注册中心,集群必须设置为true配合ribbon
    fetch-registry: true    #是否从服务端抓取已有的注册信息
    service-url:
      #集群
      #defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/
      #单机
      defaultZone: http://eureka7001.com:7001/eureka/
  instance:
    instance-id: payment8001
    prefer-ip-address: true  #访问路径可以显示IP地址
    lease-renewal-interval-in-seconds: 30  #向服务端发送心跳的时间间隔，单位为秒（默认是30秒）
    lease-expiration-duration-in-seconds: 60 #收到最后一次心跳后等待时间上限，单位为秒（默认是90秒），超时将剔除


#management:
#  endpoints:
#    web:
#      exposure:
#        include: hystrix.stream